baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ankur Sinha"
theme = "hugo-theme-learn"
googleAnalytics = "UA-128810519-1"
enableRobotsTXT = true

[params]
    author = "Author"
    title = "Ankur Sinha"
    description = "Ankur Sinha's Personal Website"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    disableBreadcrumb = true
    disableNextPrev = true
    disableInlineCopyToClipBoard = false

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false

[outputs]
    home = ["HTML", "RSS", "JSON"]

[blackfriday]
  extensions = ["hardLineBreak"]

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> GitHub"
url = "https://github.com/ansin218/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> LinkedIn"
url = "https://de.linkedin.com/in/ansin218"
weight = 12

[[menu.shortcuts]]
name = "<i class='fab fa-instagram'></i> Instagram"
url = "http://instagram.com/ansin218/"
weight = 14

[[menu.shortcuts]]
name = "<i class='fas fa-passport'></i> About Me"
url = "/cv/"
weight = 9

[[menu.shortcuts]]
name = "<i class='fas fa-server'></i> Privacy Policy"
url = "/privacy-policy"
weight = 39

[[menu.shortcuts]]
name = "<i class='fab fa-wordpress'></i> Datanalyst Info"
url = "https://www.datanalyst.info/"
weight = 40

[[menu.shortcuts]]
name = "<i class='fab fa-stack-overflow'></i> Stack Overflow"
url = "https://stackoverflow.com/users/1592364/ankur-sinha"
weight = 11