baseurl         = "/"
theme           = "duck-hugo"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Ankur Sinha"
  #subtitle    = "Port of Casper 2.x for Hugo"

  #cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = "UA-128810519-1"
  customCSS = []
  RSSLink = ""

  #twitterName = "ansin218"
  #fbName = "ansin218"
  githubName = "ansin218"

  #logo = "hugo-logo.png"
  orgName = "Ankur Sinha"

  author = "Ankur Sinha"
  authorAvatar = "img/ankur.jpeg"
  authorLocation = "Munich, DE"
  authorWebsite = "https://ankuroh.com"
  authorDescription = "Kurry Boy"
  pageNotFoundTitle = "404 - Page not found"
  singleViewStyle = "casper"

[permalinks]
  post = "/:section/:title"
  programming = "/:section/:title"
  travelogue = "/:section/:title"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Food"
  url = "/food/"
  weight = 90

[[menu.main]]
  name = "Travel"
  url = "/travelogue/"
  weight = 91

[[menu.main]]
  name = "Programming"
  url = "/programming/"
  weight = 92