baseurl         = "/"
theme           = "duck-hugo"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Ankur Sinha"
  #subtitle    = "Port of Casper 2.x for Hugo"

  #cover       = "img/blog-cover.jpg"
  description = "Ankur Sinha's Personal Website"
  metaDescription = ""
  googleAnalytics = "UA-128810519-1"
  enableRobotsTXT = true
  customCSS = []
  RSSLink = ""
  
  dateformat = "Jan 2, 2006"

  #twitterName = "ansin218"
  #fbName = "ansin218"
  githubName = "ansin218"

  #logo = "hugo-logo.png"
  orgName = "Ankur Sinha"

  author = "Ankur Sinha"
  authorAvatar = "img/ankur.jpeg"
  authorLocation = "Munich, DE"
  authorWebsite = "https://ankuroh.com"
  authorDescription = "Kurry Boy"
  pageNotFoundTitle = "404 - Page not found"
  singleViewStyle = "casper"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false

[permalinks]
  post = "/:section/:title"
  programming = "/:section/:title"
  travelogue = "/:section/:title"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Recipes"
  url = "/recipes/"
  weight = 90

[[menu.main]]
  name = "Travel"
  url = "/travelogue/"
  weight = 91

[[menu.main]]
  name = "Programming"
  url = "/programming/"
  weight = 92