[[redirects]]
  from = "https://www.ankuroh.com/programming/excel-report-automation-using-python/"
  to = "https://www.ankuroh.com/programming/automation/excel-report-automation-using-python/"
  status = 301
  force = true